name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push `ui_backend` Image
      uses: docker/build-push-action@v4
      with:
        context: ./ui_backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/yolov3_objectdetection:ui_backend

    - name: Build and Push `ai_backend` Image
      uses: docker/build-push-action@v4
      with:
        context: ./ai_backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/yolov3_objectdetection:ai_backend
