name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Build the Docker images
      run: |
        docker-compose build --no-cache --force-rm
        docker tag ui_backend ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/ui_backend:latest
        docker tag ai_backend ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/ai_backend:latest

  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images
      run: |
        docker push ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/ui_backend:latest
        docker push ${REGISTRY}/${{ secrets.DOCKER_USERNAME }}/ai_backend:latest
